### ISSUE TITLE
Suggestion for shortening the doc length

### ISSUE THREAD

**Issue by smortezah** [alidiba67/CVML#1]
Hey,

Cool repo!

My suggestion is to embed hyperlinks in single/few words rather than putting the whole link there. For example, for VGG you might wanna have:

[paper](https://arxiv.org/abs/1409.1556), [torchvision](https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py), [keras (vgg16)](https://github.com/keras-team/keras-applications/blob/master/keras_applications/vgg16.py), [keras (vgg19)](https://github.com/keras-team/keras-applications/blob/master/keras_applications/vgg19.py)

instead of

pdf: https://arxiv.org/abs/1409.1556
code: [torchvision : https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py](https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py)
code: [keras-applications : https://github.com/keras-team/keras-applications/blob/master/keras_applications/vgg16.py](https://github.com/keras-team/keras-applications/blob/master/keras_applications/vgg16.py)
code: [keras-applications : https://github.com/keras-team/keras-applications/blob/master/keras_applications/vgg19.py](https://github.com/keras-team/keras-applications/blob/master/keras_applications/vgg19.py)

This will shorten the length of the document a lot, and make it more pleasant to look at.

**Comment by alidiba67** [comment]
sure, Thanks
